### ISSUE TITLE
About Actress Costume and Accessory Data

### ISSUE THREAD

**Issue by Aceship** [MurakumoIndustries/Actress#2]
is it possible to get the JSON data for costume and accessories of the actress ?
![image](https://user-images.githubusercontent.com/5337323/41769187-a5c8a454-7638-11e8-9ba2-29c9f53b2875.png)
Currently i only found a way to get the costume (in this case ayaka costume) by its filename
but accessory name is different from costume

**Comment by WindWT** [comment]
check out accessory_base.json.txt and catalog.json.txt

**Comment by Aceship** [comment]
cant seems to find it , where is it from ?

**Comment by WindWT** [comment]
from game resource file, need unpack

**Comment by Aceship** [comment]
do you have the guide on unpacking ?

i've tried several from google but the only one i can get is just the starting screen
